### PR TITLE
#24 loginform

### LINKED ISSUE #24: login/signup form
- [x] Prompt username and password
- [x] Forgot password option
- [x] Sign up/register option
- [x] prompt email, password, name and last name for signup
- [x] terms and conditions
- [x] email validator
- [x] Integrate in navbar

### PR DESCRIPTION
**Pull request by MrMelon1232**
Added register and login form for user. 
Closes #24

### CODE REVIEW

**Review by zeinebbenmami — COMMENTED** [review]
Conflicts with PR#37 to be reviewed

**Comment by zeinebbenmami** [comment]
Conflicts Resolved

**Review by krishnnas — APPROVED** [review]
login form works. looks good.

**Review by Jonazi — APPROVED** [review]
Well-done!

**Pull request merged**
