### PR TITLE
resolves #5

### LINKED ISSUE #5: Update README file with the core features, languages and frameworks, and team members' strengths
Update the readme.md to show core features of the project  and what languages & techniques we plan to use. Include member strengths.

### PR DESCRIPTION
**Pull request by krishnnas**
Added core features, additional features
updated description and objective
added strengths

### CODE REVIEW

**Review by zeinebbenmami — APPROVED** [review]
Looks good

**Review by MrMelon1232 — APPROVED** [review]
Good enumeration of core features and readme file structure.

**Review by Jonazi — APPROVED** [review]
This is great, but there's an omission of two of the 'low-risk'  features

**Review by MohammedJava — APPROVED** [review]
Everything looks good. Don't forget to add any necessary library/framework specific to a core feature.

**Review by Shaneth549 — APPROVED** [review]
Everything looks fine.

**Review by NateTheL8 — APPROVED** [review]
Everything looks good.

**Comment by abdullahishaban** [comment]
Everything looks okay.

**Pull request merged**
