### PR TITLE
Categories and product items

### PR DESCRIPTION
**Pull request by MrMelon1232**
Added categories for home page with corresponding links. Products and rerouting will need to be added later on.

#50

### CODE REVIEW

**Comment by MohammedJava** [comment]
Added a list of laptop products with their images and card items as well as individual pages for each item

**Review by krishnnas — APPROVED** [review]
Looks great, all changes function properly.

**Review by NateTheL8 — APPROVED** [review]
Everything works, good work.

**Review by Jonazi — APPROVED** [review]
Additional files function accurately and are better organized. Nice work

**Comment by MrMelon1232** [comment]
Screenshot (34)

**Pull request merged**
